name: Publish to NPM

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.npmignore'

permissions:
  contents: write

jobs:
  publish:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Define git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - uses: pnpm/action-setup@v2
        with:
          version: 9.5.0

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Version and publish
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          if [[ "$commit_message" == *"[beta]"* ]]; then
            npm version prerelease --preid=beta
            npm publish --tag beta
          else
            npm version patch
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Push version bump
        run: git push --follow-tags